package com.basics.java;

/*
 * Every thread in java has priority. It may be default priority generated by jvm or customized priority provided by programmer
 * Range of thread priority: 1-10
 * Min: 1 
 * Max: 10
 * Thread schedulers will use the priorities to allocate processor. Thread with highest priority will get chance prior to the one having less priority
 * Thread having same priority will be allocated processors based on thread scheduler. It can Round Robin, FCS etc.
 * Default priority only for main thread is 5
 * Default priority for thread is inherited from its parent thread.
 * Some OS doesn't support thread priorities
 * */
public class ThreadPriorities {

    public static void main(String[] args) {
        MyThread t = new MyThread();
        t.setPriority(7);
        t.start();
        System.out.println(Thread.currentThread().getPriority());
        //Thread.currentThread().setPriority(12); // IllegalArgumentException as range is 1-10;
        Thread.currentThread().setPriority(6);
        System.out.println(Thread.currentThread().getPriority());
        System.out.println("Min priority: "+ Thread.MIN_PRIORITY);
        System.out.println("Max priority: "+ Thread.MAX_PRIORITY);
        System.out.println("Normal priority: "+ Thread.NORM_PRIORITY);
    }
}

class MyThread extends Thread {
    public void run() {
        System.out.println(Thread.currentThread().getPriority());
        System.out.println("Child Thread Nigga!");
    }
}